name: Python Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest-asyncio
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Download config file
        uses: carlosperate/download-file-action@v1.0.3
        with:
          file-url: ${{ secrets.CONFIG_URL }}
          file-name: ${{ secrets.CONFIG_FILE }}
      - name: Test with pytest
        run: pytest watson.py
  notify:
    name: Discord Notification
    runs-on: ubuntu-latest
    needs:
      - test
    if: ${{ always() }}
    steps:
      - name: Notify
        uses: nobrayner/discord-webhook@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: '${{ github.workflow }}: {{STATUS}}'
